package com.dicoding.c23ps051.caferecommenderapp.model

private const val region = "South Jakarta"

object CafeDummy {
    val cafeList = listOf(
        Cafe(
            "Bakerzin",
            "Central Park Mall, Letjen S. Parman No.28, RT.12/RW.6",
            22,
            "lorem ipsum sit dolor amet",
            "Bakerzin Central Park",
            10,
            "$$",
            4.8,
            "West Jakarta",
            "2752",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to true,
                Facility.IN_MALL to false,
                Facility.INDOOR to false,
                Facility.KID_FRIENDLY to true,
                Facility.LIVE_MUSIC to false,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to false,
                Facility.RESERVATION to true,
                Facility.SMOKING_AREA to true,
                Facility.TOILETS to true,
                Facility.TAKEAWAY to false,
                Facility.WIFI to false,
                Facility.PET_FRIENDLY to true,
                Facility.VIP_ROOM to false,
            )
        ),
        Cafe(
            "A",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            19,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe A",
            5,
            "$",
            4.3,
            region,
            "10000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to false,
                Facility.IN_MALL to false,
                Facility.INDOOR to true,
                Facility.KID_FRIENDLY to false,
                Facility.LIVE_MUSIC to true,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to false,
                Facility.RESERVATION to true,
                Facility.SMOKING_AREA to true,
                Facility.TOILETS to true,
                Facility.TAKEAWAY to true,
                Facility.WIFI to true,
                Facility.PET_FRIENDLY to false,
                Facility.VIP_ROOM to true,
            )
        ),
        Cafe(
            "B",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            17,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe C",
            7,
            "$$$",
            4.7,
            region,
            "25000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to true,
                Facility.IN_MALL to true,
                Facility.INDOOR to false,
                Facility.KID_FRIENDLY to true,
                Facility.LIVE_MUSIC to false,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to true,
                Facility.RESERVATION to true,
                Facility.SMOKING_AREA to true,
                Facility.TOILETS to true,
                Facility.TAKEAWAY to false,
                Facility.WIFI to false,
                Facility.PET_FRIENDLY to true,
                Facility.VIP_ROOM to true,
            )
        ),
        Cafe(
            "C",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            22,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe D",
            14,
            "$",
            4.6,
            region,
            "18000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to false,
                Facility.IN_MALL to false,
                Facility.INDOOR to true,
                Facility.KID_FRIENDLY to true,
                Facility.LIVE_MUSIC to false,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to false,
                Facility.RESERVATION to true,
                Facility.SMOKING_AREA to false,
                Facility.TOILETS to true,
                Facility.TAKEAWAY to false,
                Facility.WIFI to false,
                Facility.PET_FRIENDLY to true,
                Facility.VIP_ROOM to true,
            )
        ),
        Cafe(
            "D",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            23,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe E",
            0,
            "$",
            4.0,
            region,
            "5000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to true,
                Facility.IN_MALL to false,
                Facility.INDOOR to true,
                Facility.KID_FRIENDLY to false,
                Facility.LIVE_MUSIC to false,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to true,
                Facility.RESERVATION to false,
                Facility.SMOKING_AREA to true,
                Facility.TOILETS to false,
                Facility.TAKEAWAY to true,
                Facility.WIFI to true,
                Facility.PET_FRIENDLY to false,
                Facility.VIP_ROOM to false,
            )
        ),
        Cafe(
            "E",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            18,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe F",
            9,
            "$$",
            3.7,
            region,
            "5000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to false,
                Facility.IN_MALL to true,
                Facility.INDOOR to true,
                Facility.KID_FRIENDLY to false,
                Facility.LIVE_MUSIC to false,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to true,
                Facility.RESERVATION to true,
                Facility.SMOKING_AREA to true,
                Facility.TOILETS to false,
                Facility.TAKEAWAY to false,
                Facility.WIFI to false,
                Facility.PET_FRIENDLY to false,
                Facility.VIP_ROOM to true,
            )
        ),
        Cafe(
            "F",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            19,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe G",
            5,
            "$",
            4.3,
            region,
            "10000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to false,
                Facility.IN_MALL to false,
                Facility.INDOOR to true,
                Facility.KID_FRIENDLY to false,
                Facility.LIVE_MUSIC to true,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to false,
                Facility.RESERVATION to true,
                Facility.SMOKING_AREA to true,
                Facility.TOILETS to true,
                Facility.TAKEAWAY to true,
                Facility.WIFI to true,
                Facility.PET_FRIENDLY to false,
                Facility.VIP_ROOM to true,
            )
        ),
        Cafe(
            "G",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            0,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe H",
            23,
            "$$$",
            4.7,
            "North Jakarta",
            "25000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to true,
                Facility.IN_MALL to true,
                Facility.INDOOR to false,
                Facility.KID_FRIENDLY to true,
                Facility.LIVE_MUSIC to false,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to true,
                Facility.RESERVATION to true,
                Facility.SMOKING_AREA to true,
                Facility.TOILETS to true,
                Facility.TAKEAWAY to false,
                Facility.WIFI to false,
                Facility.PET_FRIENDLY to true,
                Facility.VIP_ROOM to true,
            )
        ),
        Cafe(
            "H",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            22,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe I",
            14,
            "$",
            4.6,
            "East Jakarta",
            "18000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to false,
                Facility.IN_MALL to false,
                Facility.INDOOR to true,
                Facility.KID_FRIENDLY to true,
                Facility.LIVE_MUSIC to false,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to false,
                Facility.RESERVATION to true,
                Facility.SMOKING_AREA to false,
                Facility.TOILETS to true,
                Facility.TAKEAWAY to false,
                Facility.WIFI to false,
                Facility.PET_FRIENDLY to true,
                Facility.VIP_ROOM to true,
            )
        ),
        Cafe(
            "I",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            23,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe J",
            0,
            "$",
            4.0,
            "East Jakarta",
            "5000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to true,
                Facility.IN_MALL to false,
                Facility.INDOOR to true,
                Facility.KID_FRIENDLY to false,
                Facility.LIVE_MUSIC to false,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to true,
                Facility.RESERVATION to false,
                Facility.SMOKING_AREA to true,
                Facility.TOILETS to false,
                Facility.TAKEAWAY to true,
                Facility.WIFI to true,
                Facility.PET_FRIENDLY to false,
                Facility.VIP_ROOM to false,
            )
        ),
        Cafe(
            "J",
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            18,
            "Jl. Raya Ragunan No. 57, Kec. Pasar Minggu, RT.5/RW.4, Kota Jakarta Selatan",
            "Cafe K",
            9,
            "$$",
            3.7,
            "Central Jakarta",
            "5000",
            "https://images.unsplash.com/photo-1685491107139-7d7f4f17b3eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=776&q=80",
            listOf(
                Facility.ALCOHOL to false,
                Facility.IN_MALL to true,
                Facility.INDOOR to true,
                Facility.KID_FRIENDLY to false,
                Facility.LIVE_MUSIC to false,
                Facility.OUTDOOR to false,
                Facility.PARKING_AREA to true,
                Facility.RESERVATION to true,
                Facility.SMOKING_AREA to true,
                Facility.TOILETS to false,
                Facility.TAKEAWAY to false,
                Facility.WIFI to false,
                Facility.PET_FRIENDLY to false,
                Facility.VIP_ROOM to true,
            )
        )
    )
}